name: Deploy to Github y Firebase

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
        
    - name: Enable Flutter web 
      run: flutter config --enable-web
      
    - name: Install dependencies
      run: flutter packages get
      
    - name: Build web
      run: flutter build web
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.token }}
        publish_dir: ./build/web

    - name: Install dependencies
      run: npm install
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}